from typing import Dict, Any, Optional
from .base import BaseInferenceAdapter, InferenceOutput

QWEN_LAND_COVER_TEXT = (
    "The main land-cover types visible in this image include:\n\n"
    "1. **Forested Areas**: The dark green regions indicate dense forest canopy and tidal mangrove complexes.\n"
    "2. **Water Bodies**: Major estuarine channels and ocean inlets, visible with distinct sediment-rich turbidity gradients.\n"
    "3. **Urban or Developed Areas**: Lighter reflectance patches along riverbanks, indicating rural settlements and infrastructure.\n"
    "4. **Dense Vegetation**: Inland vegetation and agricultural clearings displaying high vegetative index.\n\n"
    "The exact boundaries and specific types of these land-cover types vary depending on the scale and resolution of the image."
)

class MockInferenceAdapter(BaseInferenceAdapter):
    """
    Deterministic mock adapter providing authentic Qwen2.5-VL-3B-Instruct reference outputs
    for demonstrated single-image VQA and scene understanding tasks.
    Does NOT fabricate bounding boxes, segmentation masks, or fake confidence metrics for VQA.
    """

    async def run_vqa(self, image_path: str, query: str, options: Optional[Dict[str, Any]] = None) -> InferenceOutput:
        q_lower = query.lower()
        is_land_cover = "land-cover" in q_lower or "land cover" in q_lower or "vegetation" in q_lower
        
        if is_land_cover:
            summary = "Optical imagery resolves multi-class land-cover: tidal mangrove forest, estuarine water channels, and agrarian vegetation."
            raw_answer = QWEN_LAND_COVER_TEXT
            findings = [
                "Forested Areas: Dense mangrove and tidal forest canopies dominant along the delta coastline.",
                "Water Bodies: Extensive estuarine channels displaying distinct sediment gradients.",
                "Urban / Developed Patches: Settlement clusters and road clearings along waterways.",
                "Dense Vegetation: High chlorophyll spectral response throughout the inland drainage basin."
            ]
        else:
            summary = f"Analytical VQA inquiry processed: '{query}'. Demo result for single-image vision-language inspection."
            raw_answer = (
                f"Evaluation for query: \"{query}\"\n\n"
                "- Primary features: Visible surface morphology and spectral band reflectance patterns.\n"
                "- Structural dynamics: Natural drainage lines and regional surface cover.\n\n"
                "(Output generated by SatQuery Mock Inference Adapter targeting Qwen2.5-VL-3B-Instruct architecture.)"
            )
            findings = [
                f"Query matched: \"{query}\"",
                "Spectral signatures consistent with optical multispectral remote-sensing imagery.",
                "Inference evaluated via attention pooling over spatial tokens."
            ]

        return InferenceOutput(
            summary=summary,
            raw_answer=raw_answer,
            findings=findings,
            detections=[],  # Never fake bounding boxes for VQA
            segments=[],    # Never fake segmentations for VQA
            visualizations=[
                {
                    "id": "layer-base",
                    "type": "original",
                    "label": "Base Optical (Scene)",
                    "visible": True,
                    "opacity": 100,
                    "badge": "TRUECOLOR"
                }
            ],
            geojson=None,
            metrics={
                "runtimeMs": 2180,
                "confidenceScore": None,
                "confidenceLabel": "Not calibrated (Demo)",
                "detectedVessels": 0,
                "cloudOcclusionPercent": 5.0
            },
            model_name="Qwen2.5-VL-3B-Instruct",
            model_environment="DEMO / Colab-compatible"
        )

    async def run_caption(self, image_path: str, options: Optional[Dict[str, Any]] = None) -> InferenceOutput:
        summary = "Copernicus Sentinel-2 true-color surface scene featuring dynamic coastal estuaries and sediment discharge."
        raw_answer = (
            "The scene captures an intricate river delta and coastal wetlands system. Deep estuarine channels "
            "carry sediment plumes into open waters, bordered by dense mangrove forest zones and rural settlements."
        )
        findings = [
            "Coastal and estuarine delta morphology clearly defined.",
            "Sediment transport visible through turbidity discoloration.",
            "Intertidal mangrove biomes occupy low-elevation shorelines."
        ]
        return InferenceOutput(
            summary=summary,
            raw_answer=raw_answer,
            findings=findings,
            detections=[],
            segments=[],
            visualizations=[
                {
                    "id": "layer-base",
                    "type": "original",
                    "label": "Base Optical (Scene)",
                    "visible": True,
                    "opacity": 100,
                    "badge": "TRUECOLOR"
                }
            ],
            geojson=None,
            metrics={
                "runtimeMs": 1940,
                "confidenceLabel": "Not calibrated (Demo)"
            },
            model_name="Qwen2.5-VL-3B-Instruct",
            model_environment="DEMO / Colab-compatible"
        )

    async def run_change(self, image_paths: list[str], options: Optional[Dict[str, Any]] = None) -> InferenceOutput:
        return InferenceOutput(
            summary="Temporal change analysis pipeline (PLANNED / DEMO mode).",
            raw_answer="Temporal comparison requires bi-temporal registered imagery pair. Demonstration stub.",
            findings=["Multi-temporal analysis requires registered secondary acquisition."],
            detections=[],
            segments=[],
            visualizations=[],
            geojson=None,
            metrics={"runtimeMs": 500},
            model_name="ChangeFormer-V2 (Planned)",
            model_environment="DEMO / Not Connected"
        )

    async def run_fusion(self, optical_path: str, sar_path: str, options: Optional[Dict[str, Any]] = None) -> InferenceOutput:
        return InferenceOutput(
            summary="Optical-SAR fusion pipeline (PLANNED / DEMO mode).",
            raw_answer="SAR C-band cross-polarization co-registration stub.",
            findings=["SAR amplitude fusion stub."],
            detections=[],
            segments=[],
            visualizations=[],
            geojson=None,
            metrics={"runtimeMs": 600},
            model_name="Sentinel-1 SAR Fusion Engine (Planned)",
            model_environment="DEMO / Not Connected"
        )
